POST http://localhost:5001/api/register
Content-Type: application/json

{
    "username": "trong",
    "password": "123123"
}

###

POST http://localhost:5001/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123123"
}

###

POST http://localhost:5001/api/posts
Content-Type: application/json

{
    "title": "say",
    "description": "Bye bye",
    "url": "byebye.com",
    "status": "BUSY"
}

###
GET http://localhost:5001/api/search

###

GET http://localhost:5001/api/song
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODFmMWM3NmM3MmQ4ODEyMzBjMWQxZiIsImlhdCI6MTYzNzc0ODMyNiwiZXhwIjoxNjM3ODM0NzI2fQ.Z5hDP_cpj1qE43jReGpuChEf5m789ZDbM4LKPxUGrFk

###
PUT http://localhost:5001/api/rank/6198d73dfababf3eb8ee6032
Content-Type: application/json


{
    "title": "haluu",
    "author": "test",
    "image": "https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/avatars/d/0/c/6/d0c6364ef0f5565529ee23ec7559c19b.jpg"
}

###

DELETE http://localhost:5001/api/posts/6166c3e9a1686ba9c3ce5261
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTY1YTMwZmMzOTNkMWMzMzA2YzljNGQiLCJpYXQiOjE2MzQxMjQ2MjV9.ejfjEGiAeGWv75Sk0KLIC4Pcy-dx_KGY_XWhRIRaxfE

###

POST http://localhost:5001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2FiMmJiYWQxMmU5ZDNiZjUzOGE3MSIsImlhdCI6MTYzNTY4NzIyNywiZXhwIjoxNjM1NzczNjI3fQ.8kkhCVCo7HUkRxtpAnA1SKVVRUvQOwQuW2rc9lSZD-U


###

POST http://localhost:5001/api/discovery
Content-Type: application/json

{
    "img": "https://photo-resize-zmp3.zadn.vn/w320_r1x1_jpeg/avatars/d/0/c/6/d0c6364ef0f5565529ee23ec7559c19b.jpg",
    "title": "Tóm Lại Làasd",
    "author": ""
}

###
GET http://localhost:5001/api/playlist

###

DELETE http://localhost:5001/api/playlist/61ace62e1b587c4f0b027734

###

POST http://localhost:5001/api/radio
Content-Type: application/json

{
    "img": "https://photo-resize-zmp3.zadn.vn/w240_r1x1_jpeg/cover/b/c/2/1/bc2115886f2e2e9f7cf2fa28a39cda12.jpg",
    "icon": "https://photo-resize-zmp3.zadn.vn/w240_r1x1_jpeg/avatars/c/f/2/4/cf2428f7e56a8c2a52d84cb106891de2.jpg",
    "title": "K-POP",
    "listen": "1423"
}

