export const GLOBALTYPES = {
    AUTH: 'AUTH',
    ALERT: 'ALERT',
    GET_DISCOVERY: 'GET_DISCOVERY',
    GET_RADIO: 'GET_RADIO',
    GET_RANK: 'GET_RANK',
    GET_CATEGORY: 'GET_CATEGORY',
    GET_RADIO_VIEW: 'GET_RADIO_VIEW',
    GET_SONG_MUSIC: 'GET_SONG_MUSIC',
    GET_PLAYLIST: 'GET_PLAYLIST',
    POST_DISCOVERY: 'POST_DISCOVERY',
};
